FROM centos:latest
# FROM jrottenberg/ffmpeg:3.2-centos
RUN yum update -y && \
    yum -y install gcc pcre-devel openssl openssl-devel wget unzip tar git make && \
    useradd --shell /sbin/nologin nginx && \
    wget http://nginx.org/download/nginx-1.10.2.tar.gz && \
    tar -zxvf nginx-1.10.2.tar.gz && \
    wget https://github.com/arut/nginx-rtmp-module/archive/master.zip && \
    unzip master && \
    cd nginx-1.10.2 && \
    ./configure --user=www-data --group=www-data --with-http_ssl_module --with-http_realip_module --add-module=../nginx-rtmp-module-master && \
    make && \
    make install
COPY ./nginx.conf /usr/local/nginx/conf/nginx.conf
WORKDIR /usr/local/nginx/html
EXPOSE 80 1935
ENTRYPOINT ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;", "-c", "/usr/local/nginx/conf/nginx.conf"]
